### ISSUE TITLE
Dynamically creating a schema from Presentation

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/AlgebraicRewriting.jl#2]
@olynch @epatters, Kris is generating an ACSet schema from the data of a Petri Net, is there a way to avoid this `eval`? https://github.com/AlgebraicJulia/AlgebraicRewriting.jl/blob/main/docs/src/petri_to_abm.jl#L19

**Comment by kris-brown** [comment]
My understanding was that will be addressed by Owen's AnonACSets.
