### ISSUE TITLE
Rewriting every matching pattern in a graph

### ISSUE THREAD

**Issue by GeorgeR227** [AlgebraicJulia/AlgebraicRewriting.jl#9]
So I'm running into a problem where I want to rewrite all of the matching patterns in this graph:
![original](https://user-images.githubusercontent.com/78235421/195672269-75f7dcd7-647f-4089-8f7f-18e65cd763ed.svg)

This is the pattern that I'm matching for:
![match](https://user-images.githubusercontent.com/78235421/195672148-a89653eb-9347-4b39-b26a-a88fd8e5fb09.svg)

And this is the rewrite pattern, with equivalence on the respective, outermost nodes on the matching pattern and edges discarded:
![sub](https://user-images.githubusercontent.com/78235421/195672352-d49b3269-a18d-49f1-98f1-a554529d42be.svg)

After the first rewrite, the graph looks like this:
![rewrite1](https://user-images.githubusercontent.com/78235421/195672642-dc998be8-84bc-40e8-b7fa-c157ebb8cccf.svg)

But when I apply it for a second time, it performs it in the same place:
![rewrite2](https://user-images.githubusercontent.com/78235421/195672738-9b290213-a86a-4b59-bd11-6334fb3bf439.svg)
Instead I would want into to perform it on the other two original patterns before it finishes. 

What would be the best way to complete this kind of total rewrite?

**Comment by anandijain** [comment]
Yeah, I'm also running into this. My very primitive understanding is that the matching only seems to happen when vertex ids line up. If you want some very bad code that will handle this, see https://github.com/anandijain/HypergraphRewriting.jl/blob/main/test/runtests.jl
I'm almost sure that your case will work with HR.jl

I very much want to rewrite this package to use Algebraic Julia machinery, but this may be sufficient for the time being

**Comment by kris-brown** [comment]
This is now addressed by `Query` blocks in a rewriting recipe. See examples in the docs (Game of Life, Lotka Volterra) or in `test/schedules/Eval.jl` though I'll be working on actual docs (rather than just examples) in the future!
